/**
 * The compile-time lifetime composition (decisions.md §8). Not two
 * hand-written builder interfaces — one generic builder whose lifetime verbs
 * are GENERATED by a mapped type from the composed `Lifetime` members:
 *
 *   { [K in L | Lifetime.Transient as VerbName<K>]: () => ComposableBuilder<L> }
 *
 * Declare the set once, at the composition point, and the verbs exist — in
 * the type AND at runtime — only for what was composed. A composition that
 * omits `Lifetime.Scoped` has no `.scoped()` that throws; it has no
 * `.scoped()` at all. The runtime methods are folded on from the same array
 * the type derives from, so the two cannot disagree.
 *
 * Lifetime identity is the production `Lifetime` enum — never a parallel set
 * of lowercase string literals. The lowercase verb name (`.singleton()`,
 * `.scoped()`, ...) is a *mapping* from each enum member, not a second
 * vocabulary: `lifetimeVerbNames` is the one place that mapping lives.
 *
 * `Lifetime.Transient` is always expressible — it is the floor, not a
 * composed member.
 */
import { Lifetime } from '../enums';
import type { Newable, ServiceIdentifier, SourceType } from '../types';

/** The lowercase call-site verb for each production `Lifetime` member. */
const lifetimeVerbNames = {
  [Lifetime.Singleton]: 'singleton',
  [Lifetime.Scoped]: 'scoped',
  [Lifetime.Resolve]: 'resolve',
  [Lifetime.Transient]: 'transient',
} as const satisfies Record<Lifetime, string>;

/** The verb name a given `Lifetime` member maps to. */
type VerbName<L extends Lifetime> = (typeof lifetimeVerbNames)[L];

/** The lifetimes a composition may opt into. `Lifetime.Transient` is always available as the floor. */
export type ComposableLifetime = Exclude<Lifetime, Lifetime.Transient>;

/** The verbs generated for a composition, one per composed lifetime. */
export type LifetimeVerbs<L extends Lifetime> = {
  readonly [K in L as VerbName<K>]: () => ComposableBuilder<L>;
};

export type ComposableBuilder<L extends Lifetime> = {
  as(token: ServiceIdentifier<SourceType>): ComposableBuilder<L>;
} & LifetimeVerbs<L | Lifetime.Transient>;

/** One registration: the shared node every face of a `register()` call points at. */
export type ComposableNode = { readonly impl: Newable<SourceType>; lifetime?: Lifetime };

export type ComposableCollection<L extends Lifetime> = {
  readonly regs: Map<ServiceIdentifier<SourceType>, ComposableNode>;
  register(impl: Newable<SourceType>): ComposableBuilder<L>;
};

export const createCollection = <const L extends ComposableLifetime>(lifetimes: readonly L[]): ComposableCollection<L> => {
  const regs = new Map<ServiceIdentifier<SourceType>, ComposableNode>();
  const register = (impl: Newable<SourceType>): ComposableBuilder<L> => {
    // One mutable node shared by every face this register() call declares.
    const node: ComposableNode = { impl };
    const builder: Record<string, unknown> = {
      as(token: ServiceIdentifier<SourceType>) {
        regs.set(token, node);
        return builder;
      },
    };
    // The verbs are folded on from the same array the type derives from, so
    // the composed type and the composed runtime methods cannot disagree.
    for (const lifetime of [...lifetimes, Lifetime.Transient]) {
      builder[lifetimeVerbNames[lifetime]] = () => {
        node.lifetime = lifetime;
        return builder;
      };
    }
    return builder as ComposableBuilder<L>;
  };
  return { regs, register };
};
