/**
 * The compile-time lifetime composition (decisions.md §8), carrying the full
 * register-side surface — `createCollection`'s builder IS the production
 * builder: the newable/abstract overload split, `asSelf` on the newable side
 * only, `using()` in both its opaque and declared-deps forms — unified with
 * lifetime verbs GENERATED by a mapped type from the composed `Lifetime`
 * members:
 *
 *   { [K in L | Lifetime.Transient as VerbName<K>]: () => B }
 *
 * Declare the set once, at the composition point, and the verbs exist — in
 * the type AND at runtime — only for what was composed. A composition that
 * omits `Lifetime.Scoped` has no `.scoped()` that throws; it has no
 * `.scoped()` at all. The runtime methods are folded on from the same array
 * the type derives from, so the two cannot disagree.
 *
 * Lifetime identity is the production `Lifetime` enum — never a parallel set
 * of lowercase string literals. The lowercase verb name (`.singleton()`,
 * `.scoped()`, ...) is a *mapping* from each enum member, not a second
 * vocabulary: `lifetimeVerbNames` is the one place that mapping lives.
 *
 * `Lifetime.Transient` is always expressible — it is the floor, not a
 * composed member.
 *
 * A registration node IS a {@link ServiceDescriptor}, and the collection's
 * `regs` IS the {@link DescriptorMap} the graph and engine consume — one
 * registration model end to end (the Phase 17 reconciliation). Multiplicity
 * is first-class: each face `push`es the shared node under its token, so a
 * token can carry several registrations (`resolveAll`), and every face of one
 * `register()` call shares one node (one instance).
 */
import { Lifetime } from '../enums';
import { InvalidImplementationError, InvalidServiceIdentifierError, ScopedSingletonRegistrationError } from '../errors';
import { createDescriptorMap } from '../types';
import type { AbstractNewable, AsyncInstanceFactory, DescriptorMap, InstanceFactory, Newable, ResolvedDeps, ServiceDescriptor, ServiceIdentifier, SourceType } from '../types';

/** The lowercase call-site verb for each production `Lifetime` member. */
const lifetimeVerbNames = {
  [Lifetime.Singleton]: 'singleton',
  [Lifetime.Scoped]: 'scoped',
  [Lifetime.Resolve]: 'resolve',
  [Lifetime.Transient]: 'transient',
} as const satisfies Record<Lifetime, string>;

/** The verb name a given `Lifetime` member maps to. */
type VerbName<L extends Lifetime> = (typeof lifetimeVerbNames)[L];

/** The lifetimes a composition may opt into. `Lifetime.Transient` is always available as the floor. */
export type ComposableLifetime = Exclude<Lifetime, Lifetime.Transient>;

/**
 * The `.eager()` verb. Construct-at-build only makes sense for a singleton — the sole
 * build-time boundary that holds an instance (decisions.md §8) — so the verb rides on
 * a *property of the registration*: the `Eager` type flag, set `true` by `.singleton()`
 * and `false` by any other lifetime verb, and preserved across `.as()`/`.asSelf()`/
 * `.using()`. It is intersected onto the builder only while that flag is `true`, so it
 * is order-independent — `register(X).singleton().as(Y).eager()` and
 * `register(X).as(Y).singleton().eager()` both type-check — while `.scoped().eager()`
 * and `.singleton().scoped().eager()` (a later verb overriding the lifetime) are
 * compile errors, not silent no-ops. Explicit and local.
 */
type EagerVerb<B> = {
  /**
   * Construct at build rather than lazily at first resolve (decisions.md §8). Present
   * while the chosen lifetime is singleton. Returns the plain builder (the eager flag
   * is already recorded on the node), which also keeps the builder type non-recursive.
   */
  eager(): B;
};

/** The verbs generated for a newable-flavoured composition. `.singleton()` sets the `Eager` flag `true`; every other lifetime `false`. */
type NewableLifetimeVerbs<T extends SourceType, L extends Lifetime, Async extends boolean> = {
  readonly [K in L as VerbName<K>]: () => ComposableNewableBuilder<T, L, Async, K extends Lifetime.Singleton ? true : false>;
};

/** The verbs generated for an abstract-flavoured composition. `.singleton()` sets the `Eager` flag `true`; every other lifetime `false`. */
type AbstractLifetimeVerbs<T extends SourceType, L extends Lifetime, Async extends boolean> = {
  readonly [K in L as VerbName<K>]: () => ComposableAbstractBuilder<T, L, Async, K extends Lifetime.Singleton ? true : false>;
};

/**
 * The async verb, present on the builder only when the collection was composed
 * async (`createCollection(..., { async: true })`). On a sync collection it does
 * not exist at all — no verb in the type, none folded on at runtime — so async
 * intent cannot be declared where the build path could not honour it (decisions.md
 * §8). A newable-flavoured builder is returned either way, since a factory can
 * build the implementation as itself.
 */
type AsyncVerb<T extends SourceType, L extends Lifetime, Async extends boolean, Eager extends boolean> = Async extends true
  ? {
      /**
       * Supply an async factory (returns `Promise<T>`). A separate verb from `using`
       * so async intent is declared at the call site: `using(asyncFactory)` and
       * `usingAsync(syncFactory)` are each a local type error (decisions.md §8). Its
       * instance is awaited at the build boundary (`buildProviderAsync`).
       */
      usingAsync(factory: AsyncInstanceFactory<T>): ComposableNewableBuilder<T, L, Async, Eager>;
      /** Supply an async factory with declared dependencies, resolved and handed to it positionally. */
      usingAsync<const D extends readonly ServiceIdentifier<SourceType>[]>(deps: D, factory: (...args: ResolvedDeps<D>) => Promise<T>): ComposableNewableBuilder<T, L, Async, Eager>;
    }
  : unknown;

/**
 * The builder for a concrete (newable) registration. `.as()` declares a
 * resolution face and type-checks it against the implementation; `.asSelf()`
 * declares the concrete itself as a face — offered here because a newable can
 * be built as itself. `usingAsync` is present only on an async composition (see
 * {@link AsyncVerb}).
 */
export type ComposableNewableBuilder<T extends SourceType, L extends Lifetime, Async extends boolean, Eager extends boolean = false> = {
  as<F extends SourceType>(identifier: ServiceIdentifier<F> & (T extends F ? unknown : never)): ComposableNewableBuilder<T, L, Async, Eager>;
  asSelf(): ComposableNewableBuilder<T, L, Async, Eager>;
  /** Supply an opaque factory. Its dependencies are not declared, so the graph chain terminates here. */
  using(factory: InstanceFactory<T>): ComposableNewableBuilder<T, L, Async, Eager>;
  /** Supply a factory with declared dependencies, resolved and handed to it positionally. */
  using<const D extends readonly ServiceIdentifier<SourceType>[]>(deps: D, factory: (...args: ResolvedDeps<D>) => T): ComposableNewableBuilder<T, L, Async, Eager>;
} & NewableLifetimeVerbs<T, L | Lifetime.Transient, Async> & AsyncVerb<T, L, Async, Eager> & (Eager extends true ? EagerVerb<ComposableNewableBuilder<T, L, Async>> : unknown);

/**
 * The builder for an abstract registration. It has no `.asSelf()` — an
 * abstract class cannot be built as itself, so identity is declared with
 * `.as()` and the instance supplied by `.using()`. Once a factory supplies the
 * instance the registration can be built as itself, so `using()` returns the
 * newable-flavoured builder (with `asSelf`). `usingAsync` is present only on an
 * async composition (see {@link AsyncVerb}).
 */
export type ComposableAbstractBuilder<T extends SourceType, L extends Lifetime, Async extends boolean, Eager extends boolean = false> = {
  as<F extends SourceType>(identifier: ServiceIdentifier<F> & (T extends F ? unknown : never)): ComposableAbstractBuilder<T, L, Async, Eager>;
  /** Supply an opaque factory. Its dependencies are not declared, so the graph chain terminates here. */
  using(factory: InstanceFactory<T>): ComposableNewableBuilder<T, L, Async, Eager>;
  /** Supply a factory with declared dependencies, resolved and handed to it positionally. */
  using<const D extends readonly ServiceIdentifier<SourceType>[]>(deps: D, factory: (...args: ResolvedDeps<D>) => T): ComposableNewableBuilder<T, L, Async, Eager>;
} & AbstractLifetimeVerbs<T, L | Lifetime.Transient, Async> & AsyncVerb<T, L, Async, Eager> & (Eager extends true ? EagerVerb<ComposableAbstractBuilder<T, L, Async>> : unknown);

/**
 * One registration: the shared node every face of a `register()` call points
 * at. Since the Phase 17 reconciliation the node IS the production
 * {@link ServiceDescriptor} — there is no second registration model to bridge.
 */
export type ComposableNode = ServiceDescriptor<SourceType>;

export type ComposableCollection<L extends Lifetime, Async extends boolean> = {
  /** The registrations, as the {@link DescriptorMap} the graph and engine consume directly. */
  readonly regs: DescriptorMap<SourceType, Async>;
  /** Registers a concrete (newable) implementation. The returned builder offers `asSelf`. */
  register<T extends SourceType>(impl: Newable<T>): ComposableNewableBuilder<T, L, Async>;
  /** Registers an abstract implementation. The returned builder has no `asSelf` — supply an instance with `.using()`. */
  register<T extends SourceType>(impl: AbstractNewable<T>): ComposableAbstractBuilder<T, L, Async>;
  /**
   * The registrations that declared no face (no `.as()` / `.asSelf()`). They
   * never enter `regs`, so they are only visible here — `validate()` reports
   * them as `NoIdentity`.
   */
  unfaced(): ComposableNode[];
};

/** How a collection declares async intent (decisions.md §8). Omitted or `false` is a sync collection. */
export type CreateCollectionOptions<Async extends boolean> = {
  readonly async?: Async;
  /**
   * Whether this collection lives inside a scope. A scope outlives no
   * singleton table, so `.singleton()` on a scoped collection throws
   * {@link ScopedSingletonRegistrationError}.
   */
  readonly scoped?: boolean;
  /** Called once per declared face — the seam registration-time logging composes onto. */
  readonly onFace?: (token: ServiceIdentifier<SourceType>, descriptor: ComposableNode) => void;
};

export const createCollection = <const L extends ComposableLifetime, const Async extends boolean = false>(
  lifetimes: readonly L[],
  options: CreateCollectionOptions<Async> = {},
): ComposableCollection<L, Async> => {
  // Async-ness is declared here, at composition, not inferred (decisions.md §8):
  // the flag both marks the collection type — so only the async build path
  // consumes it — and folds `usingAsync` onto the builder. A sync collection has
  // no `usingAsync` at all, in the type or at runtime.
  const async = options.async === true;
  const regs = createDescriptorMap<SourceType>() as DescriptorMap<SourceType, Async>;
  const withoutFace = new Set<ComposableNode>();

  const register = <T extends SourceType>(impl: Newable<T> | AbstractNewable<T>): ComposableNewableBuilder<T, L, Async> | ComposableAbstractBuilder<T, L, Async> => {
    if (impl == null) {
      throw new InvalidImplementationError<T>(undefined);
    }
    // One mutable node — a production descriptor — shared by every face this
    // register() call declares. An un-verbed registration carries NO lifetime:
    // the engine's composed defaultLifetime supplies it (decisions.md §8).
    const node: ComposableNode = {
      implementation: impl as Newable<SourceType>,
      cacheKey: Symbol(impl.name),
      createInstance: () => new (impl as Newable<SourceType>)(),
      usesFactory: false,
    };
    withoutFace.add(node);
    const addFace = (token: ServiceIdentifier<SourceType>): void => {
      if (token == null) {
        throw new InvalidServiceIdentifierError();
      }
      withoutFace.delete(node);
      const bucket = regs.get(token);
      if (bucket === undefined) {
        regs.set(token, [node]);
      } else {
        bucket.push(node);
      }
      options.onFace?.(token, node);
    };
    const builder: Record<string, unknown> = {
      as(token: ServiceIdentifier<SourceType>) {
        addFace(token);
        return builder;
      },
      asSelf() {
        addFace(node.implementation as ServiceIdentifier<SourceType>);
        return builder;
      },
      using(depsOrFactory: InstanceFactory<SourceType> | readonly ServiceIdentifier<SourceType>[], factory?: (...args: SourceType[]) => SourceType) {
        if (typeof depsOrFactory === 'function') {
          // Opaque form: `using((scope) => Impl)`. Dependencies are not declared,
          // so the factory is opaque and the graph chain terminates at this node.
          node.createInstance = depsOrFactory;
          node.usesFactory = true;
          return builder;
        }
        // Declared-deps form: `using([deps], factory)`. The container resolves
        // each declared dep and hands them, positionally, to the factory.
        const deps = depsOrFactory;
        const build = factory as (...args: SourceType[]) => SourceType;
        node.createInstance = (scope) => build(...deps.map((dep) => scope.resolve(dep)));
        node.usesFactory = true;
        node.declaredDeps = deps;
        return builder;
      },
    };
    if (async) {
      // usingAsync exists only on an async collection — folded on from the same
      // flag the collection type is marked with, so runtime and type cannot disagree.
      builder.usingAsync = (depsOrFactory: AsyncInstanceFactory<SourceType> | readonly ServiceIdentifier<SourceType>[], factory?: (...args: SourceType[]) => Promise<SourceType>) => {
        if (typeof depsOrFactory === 'function') {
          // Opaque async form: `usingAsync((scope) => Promise<Impl>)`. Awaited at
          // the build boundary; the graph chain terminates at this node.
          node.createInstance = depsOrFactory;
          node.usesFactory = true;
          node.isAsync = true;
          return builder;
        }
        // Declared-deps async form: `usingAsync([deps], asyncFactory)`. Each dep is
        // resolved synchronously and handed, positionally, to the async factory.
        const deps = depsOrFactory;
        const build = factory as (...args: SourceType[]) => Promise<SourceType>;
        node.createInstance = (scope) => build(...deps.map((dep) => scope.resolve(dep)));
        node.usesFactory = true;
        node.isAsync = true;
        node.declaredDeps = deps;
        return builder;
      };
    }
    // `.eager()` is folded on at runtime like every other verb; the type surfaces it
    // only while the chosen lifetime is singleton (the `Eager` builder flag — see
    // {@link EagerVerb}), reachable there in any chain order but nowhere else. One
    // object carries every method; the type is the gate (as with asSelf and usingAsync).
    builder.eager = () => {
      node.eager = true;
      return builder;
    };
    // The verbs are folded on from the same array the type derives from, so
    // the composed type and the composed runtime methods cannot disagree.
    for (const lifetime of [...lifetimes, Lifetime.Transient]) {
      builder[lifetimeVerbNames[lifetime]] = () => {
        if (lifetime === Lifetime.Singleton && options.scoped === true) {
          throw new ScopedSingletonRegistrationError();
        }
        node.lifetime = lifetime;
        return builder;
      };
    }
    return builder as ComposableNewableBuilder<T, L, Async>;
  };
  return { regs, register: register as ComposableCollection<L, Async>['register'], unfaced: () => [...withoutFace] };
};

/**
 * A composed collection's registrations, typed as the {@link DescriptorMap} the
 * build functions consume. Since the reconciliation the collection's `regs` IS
 * that map — this is a name for the seam, carrying the async brand so the
 * sync/async build choice stays typed (decisions.md §8): a sync collection's
 * map builds via `buildEngine`, an async one's only via `buildEngineAsync`.
 */
export const toDescriptorMap = <L extends Lifetime, Async extends boolean>(collection: ComposableCollection<L, Async>): DescriptorMap<SourceType, Async> => collection.regs;
