packages:
  - packages/*
  - scripts
  - examples/*/*

ignoreScripts: true
minimumReleaseAge: 1440
blockExoticSubdeps: true
trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - rollup@3.30.0
  - 'semver@5.7.2 || 6.3.1'
  - ua-parser-js@1.0.41

overrides:
  '@grpc/grpc-js@<1.14.4': '>=1.14.4'
  '@opentelemetry/core@<2.8.0': ^2.8.0
  '@opentelemetry/exporter-prometheus@<0.217.0': '>=0.217.0'
  '@opentelemetry/sdk-node@<0.217.0': '>=0.217.0'
  'cookie@<0.7.0': '>=0.7.0'
  devalue@>=5.6.3 <=5.8.0: '>=5.8.1'
  'esbuild@<0.28.1': '>=0.28.1'
  follow-redirects@<=1.15.11: '>=1.16.0'
  postcss@<8.5.10: '>=8.5.10'
  protobufjs@<7.5.5: '>=7.5.5'
  'protobufjs@>=8.0.0 <=8.0.1': '>=8.0.2'
  'shell-quote@<1.8.4': '>=1.8.4'
  svelte@<=5.55.6: '>=5.55.7'
  svelte@>=5.46.0 <=5.55.6: '>=5.55.7'
  svelte@>=5.51.5 <=5.55.6: '>=5.55.7'
  'uuid@<11.1.1': '>=11.1.1'

packageExtensions:
  'applicationinsights@3.3.0':
    dependencies:
      undici: '^6'

minimumReleaseAgeExclude:
  - vite@7.3.5
  - '@opentelemetry/core@2.8.0'
  - http-proxy-middleware@3.0.7
  - undici@6.27.0
  - http-proxy-middleware@3.0.6
  - js-yaml@3.15.0
  - js-yaml@4.1.2
  - ws@8.21.0
  - protobufjs@8.4.3
  - protobufjs@8.4.1
  - protobufjs@7.6.1
  - protobufjs@8.5.1
  - protobufjs@7.6.3
  - '@babel/core@7.29.1'
