/**
 * Layer 4 — the composable builder. Depends on: types.
 *
 * NOT two hand-written interfaces. One generic builder whose lifetime verbs
 * are GENERATED by a mapped type from the composed lifetime names:
 *
 *   { [K in L | 'transient']: () => ComposableBuilder<L> }
 *
 * Declare the set once, at the composition point, and the verbs exist — in
 * the type AND at runtime — only for what was composed. Lite's builder does
 * not have a .scoped() that throws; it has no .scoped() at all. The runtime
 * methods are folded on from the same array the type derives from, so the
 * two cannot disagree.
 *
 * 'transient' is always expressible: it is the floor, not a member.
 */
import type { Impl, LifetimeName, Node, Token } from './types';

/** The verbs, generated from the composed names. */
export type LifetimeVerbs<L extends string> = {
  readonly [K in L]: () => ComposableBuilder<L>;
};

export type ComposableBuilder<L extends string> = {
  as(token: Token): ComposableBuilder<L>;
} & LifetimeVerbs<L | 'transient'>;

export type ComposableCollection<L extends string> = {
  readonly regs: Map<Token, Node>;
  register(impl: Impl): ComposableBuilder<L>;
};

export const createCollection = <const L extends Exclude<LifetimeName, 'transient'>>(lifetimes: readonly L[]): ComposableCollection<L> => {
  const regs = new Map<Token, Node>();
  const register = (impl: Impl): ComposableBuilder<L> => {
    // One mutable node shared by every face this register call declares.
    const node: { impl: Impl; lifetime?: LifetimeName } = { impl };
    const builder: Record<string, unknown> = {
      as(token: Token) {
        regs.set(token, node as Node);
        return builder;
      },
    };
    // The verbs are folded on from the same array the type derives from.
    for (const lifetime of [...lifetimes, 'transient' as const]) {
      builder[lifetime] = () => {
        node.lifetime = lifetime;
        return builder;
      };
    }
    return builder as ComposableBuilder<L>;
  };
  return { regs, register };
};
