import { Feature } from '../enums';
import type { SupportedFormat } from './resolveFormat';
import type { ResolvedOptions } from './types';

export const generateVirtualModule = (options: ResolvedOptions, format: SupportedFormat): string => {
  const lines: string[] = ['/**', ' * @generated by @shellicar/build-azure-local-settings', ` * @generated-at ${new Date().toISOString()}`, ' * WARNING: This code is auto-generated. Do not edit manually.', ' */', ''];

  if (format === 'esm' && options.features[Feature.CjsShimAutoInclude]) {
    lines.push("import '@shellicar/build-azure-local-settings/cjs-shim';");
  }

  for (const importPath of options.sideEffectImports) {
    lines.push(`import '${importPath}';`);
  }

  let exportName: string;
  if (options.mainExport === 'default') {
    exportName = 'main';
    lines.push(`import ${exportName} from '${options.mainModule}';`);
  } else {
    exportName = options.mainExport;
    lines.push(`import { ${exportName} } from '${options.mainModule}';`);
  }

  if (options.loadLocalSettings) {
    lines.push("import { loadLocalSettings } from '@shellicar/build-azure-local-settings/runtime';");
  }

  lines.push('');

  const asyncLines: string[] = [];
  if (options.loadLocalSettings) {
    asyncLines.push('await loadLocalSettings();');
  }
  asyncLines.push(`await ${exportName}();`);

  if (format === 'cjs') {
    lines.push('(async () => {');
    for (const line of asyncLines) {
      lines.push(`  ${line}`);
    }
    lines.push('})();');
  } else {
    for (const line of asyncLines) {
      lines.push(line);
    }
  }

  return lines.join('\n');
};
